### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mr0os** [mjnaderi/mjnaderi#1]
بسیار حوشم اومد و اونو فورک کردم ام mjnaderi   با سلام و احترام خدمت شما آقای نادری بنده از پروژه 
اما بنده سوالی که داشتم این بود که چطور میتونم وضعیت گیت هاب رو  به این صورت آنلاین نمایش بدم اگر  راهنمایی بفرماید ممنون میشم بازم ممنون

**کار کردن روی این پروژه از جمله افتخارات بنده هست**

**Comment by mjnaderi** [comment]
This is not my project. It's a feature of GitHub. You don't need to fork my repo. You can create your own profile README easily:

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme

**Comment by Mr0os** [comment]
Thanks
